name: yourdailylight
description: "Your Daily Light App"


version: 1.1.56+56

environment:
  #sdk: ^3.6.1
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  fast_i18n: ^5.11.0
  easy_dialog: ^1.1.0
  sqflite: ^2.0.2
  dio: ^5.3.2
  provider: ^6.0.2
  transparent_image: ^2.0.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^10.1.0
  line_awesome_flutter: ^3.0.1
  #better_player: ^0.0.84
  #youtube_player_flutter: ^8.1.0
 # youtube_player_flutter_quill: ^8.2.2
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  firebase_auth: ^5.3.3
  #firebase_messaging: ^13.0.0
  flutter_local_notifications: ^19.4.0
  #google_mobile_ads: ^2.0.1
  shared_preferences: ^2.0.13
  #sign_in_apple: ^2.0.0    ---TO SETUP
  google_sign_in: ^6.1.4
  email_validator: ^3.0.0
  shimmer: ^3.0.0
  #audiofileplayer: ^2.1.0
  palette_generator: ^0.3.3
  file_utils: ^1.0.0
  permission_handler: ^12.0.0+1
  path_provider: ^2.0.9
  flutter_downloader: ^1.7.2
  #in_app_purchase: ^3.0.1
  share_plus: ^11.0.0
 # package_info: ^2.0.2
  #in_app_review: ^2.0.6
  #flutter_web_browser: ^0.17.1
  lottie: ^3.0.0
  flutter_widget_from_html: ^0.16.0
  # select_dialog: ^2.0.0
  #flutter_tts: ^3.2.2
  clipboard: ^0.1.3
  translator: ^1.0.0
  flutter_sticky_header: ^0.8.0
  flutter_material_color_picker: ^1.1.0+2
    #dynamic_text_highlighting: ^2.2.0
    #media_picker_widget: ^0.0.7
    #flutter_absolute_path:
    #git:
  # url: https://github.com/canewsin/flutter_absolute_path.git

  smooth_page_indicator: ^1.0.0+2
  visibility_detector: ^0.4.0+2
  file_picker: ^10.0.0
  event_bus: ^2.0.0
  photo_view: ^0.15.0
  #flutter_login_facebook: ^1.4.1
  #vimeoplayer_trinity: ^0.1.9
  #flutter_quill: ^6.1.12
  intl: ^0.20.2
  flash: ^3.0.5+1
  highlight_text: ^1.3.0
  #firebase_core_platform_interface: 4.5.1
  firebase_core_platform_interface: ^5.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  collection: ^1.15.0-nullsafety.4

  #New Dependencies and library
  #epubx: ^3.0.0
  #epub_view: ^3.0.0
  nb_utils: ^7.0.4
  #vocsy_epub_viewer: ^0.0.8
  just_audio: ^0.9.30
  #epub_view: ^3.0.0
  #epub_parser: ^3.0.1
  #flutter_html: ^2.0.0
  #pdf: ^3.8.4
  syncfusion_flutter_pdfviewer: ^30.1.41
  #audioplayers: ^1.1.1
  just_audio_background: ^0.0.1-beta.7
  flutter_native_splash: ^2.4.6
  url_launcher: ^6.1.2
  #open_mail_app: ^0.4.5
  #flutter_share: ^2.0.0
  #flutter_share: ^2.0.0
  flutter_rating_bar: ^4.0.0

  ##psymnrt
  #flutter_paypal: ^0.2.0



  path: any
  http: any
  logging: any
  fluttertoast: any
  flutter_svg: any
  #webview_flutter: any
  audio_session: any

  rxdart: any
  html: any
  #wakelock: any
  wakelock_plus: ^1.2.8
  package_info_plus: ^8.2.1

  #Daily update
  timezone: ^0.10.0
  #flutter_native_timezone: ^2.0.0
  flutter_timezone: ^4.1.0

  # To Auto push update on Live
  shorebird_code_push: ^2.0.4
  audio_service: ^0.18.18
  #workmanager: ^0.8.0
  alarm: ^5.1.4
 # android_alarm_manager_plus: ^4.0.7
  android_intent_plus: ^5.3.0
  device_info_plus: ^11.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: ^6.0.0
  webview_flutter: ^4.10.0



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/raw/
    - assets/images/landing.png
    - assets/images/logo_android12.png
    - assets/lottie/
    - shorebird.yaml


  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#30687f"
  background_image: "assets/images/landing.png"
  android_12:
    image: "assets/images/logo_android12.png"
    icon_background_color: "#30687f"
